### ISSUE TITLE
Building a docker image using compose.yml prompts the following error

### ISSUE THREAD

**Issue by ruoshui9527** [fantasy-peak/cpp-freegpt-webui#32]
Building a docker image using compose.yml prompts the following error
compose.yml
```
version: "3.9"
services:
  fantasypeak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantasypeak
    image: fantasypeak/freegpt:latest
    ports:
      - "8858:8858"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - HTTP_PROXY=http://localhost
      - CHAT_PATH=/chat
```

Step 10/16 : ADD bin /app/bin
ADD failed: file not found in build context or excluded by .dockerignore: stat bin: file does not exist
ERROR: Service 'fantasypeak' failed to build : Build failed.

There is also no bin folder in the code
